// SPDX-License-Identifier: GPL-2.0-or-later
//
// From Arcade-ITech32_MiSTer (TheJesusFish), rtl/itech32/itech32_tg68_bus_adapter.sv
// at d461e21d. Local changes for Arcade-NMKMacPlus_MiSTer: renamed; the
// reset-vector shadow at 0x00-0x7F is a parameter (VECTOR_SHADOW, off here:
// this board's vectors are in ROM); the locally completed IACK cycle is
// exported as a one-clock `iack` with its level, so the board can retire a
// held interrupt (MS1-23).
//
// Bridge the 16-bit TG68K.C bus to the core's 32-bit, big-endian board bus.
// TG68K.C advances only when tg_clkena is asserted.  A transaction is
// therefore captured once, held stable for an arbitrarily long board stall,
// and acknowledged to the CPU on a later cpu_ce pulse.

module macplus_tg68_bus_adapter #(
	parameter VECTOR_SHADOW = 0
) (
	input  logic        clk,
	input  logic        reset,
	input  logic        cpu_ce,

	input  logic [1:0]  tg_busstate,
	input  logic [2:0]  tg_fc,
	input  logic [31:0] tg_addr,
	input  logic [15:0] tg_wdata,
	input  logic        tg_nuds,
	input  logic        tg_nlds,
	output logic        tg_clkena,
	output logic [15:0] tg_rdata,

	// MAME's ITech32 driver copies the first 0x80 program-ROM bytes to
	// address zero before releasing the 68EC020.  This loader-facing shadow
	// provides the same reset-vector window without a second board-bus master.
	input  logic        vector_load_we,
	input  logic [4:0]  vector_load_addr,
	input  logic [31:0] vector_load_wdata,
	input  logic [3:0]  vector_load_be,

	output logic        board_req,
	output logic        board_we,
	output logic [23:0] board_addr,
	output logic [31:0] board_wdata,
	output logic [3:0]  board_be,
	input  logic        board_ack,
	input  logic [31:0] board_rdata,
	output logic        iack,
	output logic [2:0]  iack_level
);

	typedef enum logic [2:0] {
		IDLE,
		MAP_CAPTURE,
		VECTOR_ACCESS,
		WAIT_BOARD,
		HAVE_RESPONSE
	} state_t;

	state_t state;
	logic [31:0] vector_ram [0:31];

	logic [23:0] mapped_word_addr;
	logic [23:0] mapped_byte_addr;
	logic [31:0] mapped_wdata;
	logic [3:0]  mapped_be;
	logic [15:0] selected_board_rdata;
	logic        tg_cycle_active;
	logic        tg_cycle_strobed;
	logic        captured_cycle_write;
	logic        captured_cycle_vector;
	logic        captured_cycle_iack;

	// TG68's address is generated by a substantial internal adder.  Capture the
	// raw, already-stable CPU cycle before doing the vector-window comparison and
	// 16-to-32-bit lane mapping so neither cone can be absorbed into a downstream
	// board RAM's input registers by physical synthesis.
	logic [1:0]  captured_busstate;
	logic [2:0]  captured_fc;
	logic [31:0] captured_addr;
	logic [15:0] captured_wdata;
	logic        captured_nuds;
	logic        captured_nlds;

	logic        held_we;
	logic [23:0] held_addr;
	logic [31:0] held_wdata;
	logic [3:0]  held_be;
	logic [4:0]  vector_index_q;
	logic        vector_lower_q;
	logic        vector_write_q;
	logic [31:0] vector_wdata_q;
	logic [3:0]  vector_be_q;

	function automatic logic [31:0] merge_bytes(
		input logic [31:0] old_value,
		input logic [31:0] new_value,
		input logic [3:0] enables
	);
		logic [31:0] result;
		integer lane;
		begin
			result = old_value;
			for (lane = 0; lane < 4; lane = lane + 1)
				if (enables[lane])
					result[lane*8 +: 8] = new_value[lane*8 +: 8];
			merge_bytes = result;
		end
	endfunction

	always_comb begin
		tg_cycle_active = (tg_busstate != 2'b01);
		// At the 6x-pixel fabric rate the 25 MHz NCO can request two
		// consecutive TG68 steps.  TG68 may assert busstate one step before
		// memmaskmux has produced a byte strobe; that is a legal internal
		// transition, not a bus transfer.  Stop further CPU advancement as soon
		// as busstate becomes active, but capture only the first strobed phase.
		tg_cycle_strobed = tg_cycle_active && (!tg_nuds || !tg_nlds);
		captured_cycle_write  = (captured_busstate == 2'b11);
		captured_cycle_vector = VECTOR_SHADOW && (captured_addr < 32'h0000_0080);
		// TG68K.C still emits the 68020 CPU-space acknowledge cycle when
		// IPL_autovector is asserted; it merely ignores returned vector data.
		// Keep that FC=111 read out of the 24-bit board address space and
		// complete it locally.  Writes and ordinary FC values still forward.
		captured_cycle_iack = !captured_cycle_write &&
			(captured_fc == 3'b111) &&
			(captured_addr[31:4] == 28'hfff_ffff);

		// TG68K presents a 16-bit word bus.  nUDS selects the even-addressed
		// byte and nLDS the odd-addressed byte, regardless of dword half.
		mapped_word_addr = {captured_addr[23:1], 1'b0};
		mapped_wdata     = captured_addr[1] ? {16'h0000, captured_wdata}
		                                       : {captured_wdata, 16'h0000};
		mapped_be        = captured_addr[1] ? {2'b00, ~captured_nuds, ~captured_nlds}
		                                       : {~captured_nuds, ~captured_nlds, 2'b00};

		// Keep byte-register decodes exact (for example sound command at
		// 0x480001), while word accesses remain even aligned.
		if (captured_nuds && !captured_nlds)
			mapped_byte_addr = mapped_word_addr + 24'd1;
		else
			mapped_byte_addr = mapped_word_addr;

		selected_board_rdata = board_addr[1] ? board_rdata[15:0]
		                                                   : board_rdata[31:16];

		// Advance a no-memory-access CPU step or completed response on the
		// requested cadence.  This must be a live guard at the 6x-pixel fabric
		// rate: a registered copy would remain high for one extra edge when the
		// 25 MHz NCO emits consecutive enables, stepping TG68 past a newly
		// asserted bus cycle.
		tg_clkena = !reset && cpu_ce &&
		             (((state == IDLE) && !tg_cycle_active) ||
		              (state == HAVE_RESPONSE));
	end

	// This payload is overwritten on every active-cycle capture before
	// MAP_CAPTURE can consume it, so it needs no reset value.  Keeping it in a
	// CE-only bank prevents reset muxing and physical retiming from rebuilding
	// the TG68 write-data path through the adapter boundary.
	always_ff @(posedge clk) begin
		if (!reset && (state == IDLE) && tg_cycle_strobed)
			captured_wdata <= tg_wdata;
	end

	always_ff @(posedge clk) begin
		// The loader is intentionally independent of reset: software fills the
		// reset-vector shadow while the CPU is held in reset.
		if (vector_load_we)
			vector_ram[vector_load_addr] <= merge_bytes(
				vector_ram[vector_load_addr], vector_load_wdata, vector_load_be);

		if (reset) begin
			state       <= IDLE;
			board_req   <= 1'b0;
			board_we    <= 1'b0;
			board_addr  <= 24'd0;
			board_wdata <= 32'd0;
			board_be    <= 4'd0;
			tg_rdata    <= 16'hffff;
			held_we     <= 1'b0;
			held_addr   <= 24'd0;
			held_wdata  <= 32'd0;
			held_be     <= 4'd0;
			captured_busstate <= 2'b01;
			captured_fc       <= 3'b000;
			captured_addr     <= 32'd0;
			captured_nuds     <= 1'b1;
			captured_nlds     <= 1'b1;
			vector_index_q     <= 5'd0;
			vector_lower_q     <= 1'b0;
			vector_write_q     <= 1'b0;
			vector_wdata_q     <= 32'd0;
			vector_be_q        <= 4'd0;
			iack               <= 1'b0;
			iack_level         <= 3'd0;
		end else begin
			iack <= 1'b0;
			case (state)
				IDLE: begin
					board_req <= 1'b0;
					// TG changes its bus only when tg_clkena is asserted.  Once an
					// active cycle appears it is therefore safe to capture on the next
					// fabric edge, without waiting for another cpu_ce pulse.
					if (tg_cycle_strobed) begin
						captured_busstate <= tg_busstate;
						captured_fc       <= tg_fc;
						captured_addr     <= tg_addr;
						captured_nuds     <= tg_nuds;
						captured_nlds     <= tg_nlds;
						state             <= MAP_CAPTURE;
					end
				end

				MAP_CAPTURE: begin
					if (captured_cycle_iack) begin
						iack <= 1'b1; iack_level <= captured_addr[3:1];
						tg_rdata <= 16'hffff;
						state <= HAVE_RESPONSE;
					end else if (captured_cycle_vector) begin
						// Isolate the captured-address compare/lane-mapping cone from
						// the vector RAM's address, data, and write-enable ports.
						vector_index_q <= captured_addr[6:2];
						vector_lower_q <= captured_addr[1];
						vector_write_q <= captured_cycle_write;
						vector_wdata_q <= mapped_wdata;
						vector_be_q <= mapped_be;
						state <= VECTOR_ACCESS;
					end else begin
						board_req   <= 1'b1;
						board_we    <= captured_cycle_write;
						board_addr  <= mapped_byte_addr;
						board_wdata <= mapped_wdata;
						board_be    <= mapped_be;
						held_we     <= captured_cycle_write;
						held_addr   <= mapped_byte_addr;
						held_wdata  <= mapped_wdata;
						held_be     <= mapped_be;
						state        <= WAIT_BOARD;
					end
				end

				VECTOR_ACCESS: begin
					if (vector_write_q && !vector_load_we)
						vector_ram[vector_index_q] <= merge_bytes(
							vector_ram[vector_index_q], vector_wdata_q, vector_be_q);
					else if (!vector_write_q)
						tg_rdata <= vector_lower_q
							? vector_ram[vector_index_q][15:0]
							: vector_ram[vector_index_q][31:16];
					state <= HAVE_RESPONSE;
				end

				WAIT_BOARD: begin
					if (board_ack) begin
						if (!board_we)
							tg_rdata <= selected_board_rdata;
						board_req <= 1'b0;
						state     <= HAVE_RESPONSE;
					end
				end

				HAVE_RESPONSE: begin
					// Advance the adapter on the same edge that TG68 consumes the
					// registered enable pulse.
					if (tg_clkena)
						state <= IDLE;
				end

				default: begin
					state     <= IDLE;
					board_req <= 1'b0;
				end
			endcase
		end
	end

`ifndef SYNTHESIS
	always_ff @(posedge clk) begin
		if (!reset && state == MAP_CAPTURE)
			assert (!captured_nuds || !captured_nlds)
				else $fatal(1, "TG68 captured a cycle without byte strobes");
		if (!reset && state == WAIT_BOARD) begin
			assert (board_req)
				else $fatal(1, "board request dropped before acknowledge");
			assert ({board_we, board_addr, board_wdata, board_be} ==
			        {held_we, held_addr, held_wdata, held_be})
				else $fatal(1, "board controls changed while stalled");
		end
	end
`endif

endmodule
