// Savestate gate harness top (SS-13's method, docs/PLAN.md 2.9): the core
// and the savestate engine (VARLAT=1) with its DDR port brought out to the
// C++ model. The core's ports pass through under their own names (generated
// from macplus_core's port list by gen_ss_top.py; rerun it when those change).
module ss_top (
	input             clk,
	input             reset,
	input             quiz,
	input             pause,
	input             flip,
	input      [31:0] inputs,
	input      [15:0] dsw,
	input             ram2_sel,
	input      [14:0] ram2_addr,
	input             ram2_we,
	input      [3:0]  ram2_be,
	input      [31:0] ram2_din,
	output     [31:0] ram2_dout,
	output            mrom_req,
	output     [19:0] mrom_addr,
	input             mrom_ack,
	input      [31:0] mrom_data,
	output            srom_req,
	output     [18:0] srom_addr,
	input             srom_ack,
	input      [15:0] srom_data,
	output     [3:0]  bg_req,
	output     [91:0] bg_addr,
	input      [3:0]  bg_ready,
	input      [3:0]  bg_valid,
	input     [127:0] bg_data,
	output            spr_req,
	output     [23:0] spr_addr,
	input             spr_ready,
	input             spr_valid,
	input     [127:0] spr_data,
	output            smp_req,
	output     [1:0]  smp_bank,
	output     [20:0] smp_word,
	input             smp_ack,
	input      [15:0] smp_data,
	output            ce_pix,
	output     [8:0]  hcount,
	output     [8:0]  vcount,
	output            hblank,
	output            vblank,
	output            hsync,
	output            vsync,
	output     [23:0] rgb,
	output     [23:0] rgb_fade,
	output signed [15:0] snd_l,
	output signed [15:0] snd_r,
	output     [31:0] dbg_irq3,
	output     [31:0] dbg_iack3,
	output     [31:0] dbg_idle,
	output     [31:0] dbg_work,
	input             trace_on,
	output     [31:0] dbg_es_writes,
	output     [31:0] dbg_es_irq,
	output     [31:0] dbg_latch_reads,
	output [31:0] dbg_latch_writes,
	output     [31:0] dbg_cpu_addr,
	output     [15:0] dbg_spr_max_cycles,
	output     [15:0] dbg_spr_overruns,
	output     [63:0] dbg_bg_overruns,
	input             save_req,
	input             load_req,
	input      [1:0]  slot,
	output            ss_busy,
	output            ss_done_ok,
	output            ss_done_fail,
	output     [1:0]  ss_fail_code,
	output            ddr_we,
	output            ddr_rd,
	output     [28:0] ddr_addr,
	output     [63:0] ddr_din,
	input      [63:0] ddr_dout,
	input             ddr_dout_ready
);
	wire        ss_freeze, ss_resume, ss_active, ss_rd, ss_wr, ss_ack, ss_frozen, ss_parked, ss_replay, ss_replay_done;
	wire [19:0] ss_addr;
	wire [15:0] ss_rdata, ss_wdata;
	macplus_core u_core (.*);
	savestate #(.SS_WORDS(20'h24900), .DDR_BASE(29'd0), .SLOT_STRIDE(29'h10000), .VARLAT(1)) u_ss (
		.clk(clk), .reset(reset), .save_req(save_req), .load_req(load_req), .slot(slot), .vblank(vblank), .allow(!reset),
		.ss_freeze(ss_freeze), .ss_frozen(ss_frozen), .ss_parked(ss_parked), .ss_resume(ss_resume), .ss_active(ss_active),
		.ss_addr(ss_addr), .ss_rdata(ss_rdata), .ss_wr(ss_wr), .ss_rd(ss_rd), .ss_ack(ss_ack), .ss_wdata(ss_wdata),
		.ss_replay(ss_replay), .ss_replay_done(ss_replay_done),
		.busy(ss_busy), .done_ok(ss_done_ok), .done_fail(ss_done_fail), .fail_code(ss_fail_code), .was_load(),
		.clk_ddr(clk), .ddr_busy(1'b0), .rot_we(1'b0), .ddr_we(ddr_we), .ddr_rd(ddr_rd), .ddr_addr(ddr_addr),
		.ddr_din(ddr_din), .ddr_dout(ddr_dout), .ddr_dout_ready(ddr_dout_ready));
endmodule
